using Microsoft.Extensions.Localization;
using System.Globalization;

namespace HotelReservationSystem.Resources;

/// <summary>
/// Custom IStringLocalizer backed by hardcoded dictionaries.
/// Bypasses .resx file lookup entirely — 100% cross-platform reliable.
/// </summary>
public class HardcodedStringLocalizer : IStringLocalizer
{
    private static readonly Dictionary<string, string> _en = new()
    {
        // Navigation
        ["Nav_Dashboard"] = "Dashboard",
        ["Nav_Calendar"] = "Calendar",
        ["Nav_Properties"] = "Properties",
        ["Nav_Reservations"] = "Reservations",
        ["Nav_Reports"] = "Reports",
        ["Nav_SignIn"] = "Sign In",
        ["Nav_SignOut"] = "Sign Out",
        ["Nav_MyProfile"] = "My Profile",
        ["Nav_ChangePassword"] = "Change Password",
        ["Nav_UserManagement"] = "User Management",
        ["Nav_Settings"] = "Settings",
        ["Nav_HelpSupport"] = "Help & Support",
        ["Nav_Notifications"] = "Notifications",
        ["Nav_Home"] = "Home",
        ["Nav_Bookings"] = "Bookings",
        ["Nav_Profile"] = "Profile",
        // Language selector
        ["Lang_SelectLanguage"] = "Language",
        ["Lang_English"] = "English",
        ["Lang_Spanish"] = "Español",
        // Common
        ["Common_Loading"] = "Loading...",
        ["Common_Save"] = "Save",
        ["Common_Cancel"] = "Cancel",
        ["Common_Edit"] = "Edit",
        ["Common_Delete"] = "Delete",
        ["Common_Close"] = "Close",
        ["Common_Refresh"] = "Refresh",
        ["Common_ViewAll"] = "View All",
        ["Common_Details"] = "Details",
        ["Common_Back"] = "Back",
        ["Common_Yes"] = "Yes",
        ["Common_No"] = "No",
        ["Common_All"] = "All",
        ["Common_Search"] = "Search",
        ["Common_Filter"] = "Filter",
        ["Common_Reset"] = "Reset",
        ["Common_Error"] = "An error occurred. Please try again.",
        ["Common_Success"] = "Operation completed successfully.",
        ["Common_Required"] = "This field is required.",
        ["Common_Saving"] = "Saving...",
        ["Common_Modify"] = "Modify",
        ["Common_NoData"] = "No data available",
        // Admin Login
        ["Login_Title"] = "Sign In",
        ["Login_WelcomeBack"] = "Welcome Back",
        ["Login_Subtitle"] = "Please sign in to your account",
        ["Login_Email"] = "Email address",
        ["Login_Password"] = "Password",
        ["Login_RememberMe"] = "Remember me",
        ["Login_ForgotPassword"] = "Forgot password?",
        ["Login_SignIn"] = "Sign In",
        ["Login_SigningIn"] = "Signing in...",
        ["Login_NeedHelp"] = "Need help?",
        ["Login_ContactAdmin"] = "Contact your system administrator for account access",
        ["Login_SmartBooking"] = "Smart Booking",
        ["Login_Analytics"] = "Analytics",
        ["Login_Secure"] = "Secure",
        ["Login_SystemTitle"] = "Hotel Reservation System",
        ["Login_SystemSubtitle"] = "Centralized management for all your hotel reservations",
        // Dashboard
        ["Dashboard_Title"] = "Dashboard",
        ["Dashboard_DateRange"] = "Date Range",
        ["Dashboard_AllHotels"] = "All Hotels",
        ["Dashboard_AutoRefresh"] = "Auto-refresh",
        ["Dashboard_AddWidget"] = "Add Widget",
        ["Dashboard_SaveLayout"] = "Save Layout",
        ["Dashboard_ResetLayout"] = "Reset",
        ["Dashboard_SelectWidget"] = "Select a widget to add to your dashboard. Already-visible widgets are greyed out.",
        ["Dashboard_LoadingWidgets"] = "Loading widgets…",
        // Notifications
        ["Notif_Title"] = "Notification Center",
        ["Notif_Subtitle"] = "Manage and review all your notifications",
        ["Notif_Settings"] = "Settings",
        ["Notif_MarkAllRead"] = "Mark all read",
        ["Notif_Total"] = "Total",
        ["Notif_Unread"] = "Unread",
        ["Notif_Today"] = "Today",
        ["Notif_Read"] = "Read",
        ["Notif_All"] = "All",
        ["Notif_Reservations"] = "Reservations",
        ["Notif_Alerts"] = "Alerts",
        ["Notif_AllTypes"] = "All types",
        ["Notif_Empty"] = "No notifications found",
        ["Notif_LoadingMore"] = "Loading more…",
        ["Notif_AllLoaded"] = "All notifications loaded",
        ["Notif_MarkRead"] = "Mark read",
        ["Notif_JustNow"] = "Just now",
        ["Notif_Notifications"] = "Notifications",
        ["Notif_MarkAllReadBtn"] = "Mark all read",
        ["Notif_ViewAll"] = "View all",
        ["Notif_NoNotifications"] = "No notifications",
        // Notification Settings
        ["NotifSettings_Title"] = "Notification Settings",
        ["NotifSettings_Subtitle"] = "Configure how and when you receive notifications",
        ["NotifSettings_Channels"] = "Notification Channels",
        ["NotifSettings_ChannelsDesc"] = "Choose how you want to receive notifications.",
        ["NotifSettings_Email"] = "Email",
        ["NotifSettings_EmailDesc"] = "Receive notifications via email",
        ["NotifSettings_Sms"] = "SMS",
        ["NotifSettings_SmsDesc"] = "Receive text message notifications",
        ["NotifSettings_BrowserPush"] = "Browser Push",
        ["NotifSettings_BrowserPushDesc"] = "Receive browser push notifications",
        ["NotifSettings_Events"] = "Notification Events",
        ["NotifSettings_EventsDesc"] = "Choose which events trigger notifications.",
        ["NotifSettings_BookingConf"] = "Booking Confirmations",
        ["NotifSettings_BookingConfDesc"] = "When a reservation is created",
        ["NotifSettings_CheckIn"] = "Check-in Reminders",
        ["NotifSettings_CheckInDesc"] = "24 hours before check-in",
        ["NotifSettings_CheckOut"] = "Check-out Reminders",
        ["NotifSettings_CheckOutDesc"] = "On the day of check-out",
        ["NotifSettings_Modification"] = "Modification Confirmations",
        ["NotifSettings_ModificationDesc"] = "When a reservation is modified",
        ["NotifSettings_Promo"] = "Promotional Offers",
        ["NotifSettings_PromoDesc"] = "Special deals and promotions",
        ["NotifSettings_SavePrefs"] = "Save Preferences",
        ["NotifSettings_Saving"] = "Saving…",
        ["NotifSettings_Saved"] = "Preferences saved successfully",
        ["NotifSettings_SaveFailed"] = "Failed to save preferences",
        // Guest Portal Layout
        ["GP_GuestPortal"] = "Guest Portal",
        ["GP_SignIn"] = "Sign In",
        ["GP_SignOut"] = "Sign Out",
        ["GP_Dashboard"] = "Dashboard",
        ["GP_MyReservations"] = "My Reservations",
        ["GP_MyProfile"] = "My Profile",
        ["GP_AuthRequired"] = "Please sign in to access your guest portal.",
        ["GP_Home"] = "Home",
        ["GP_Bookings"] = "Bookings",
        ["GP_Profile"] = "Profile",
        // Guest Portal Login
        ["GP_Login_Title"] = "Guest Sign In",
        ["GP_Login_Subtitle"] = "Access your reservations & profile",
        ["GP_Login_WelcomeBack"] = "Welcome back",
        ["GP_Login_Desc"] = "Sign in with your email and booking reference",
        ["GP_Login_Email"] = "Email Address",
        ["GP_Login_BookingRef"] = "Booking Reference",
        ["GP_Login_BookingRefHint"] = "Found in your booking confirmation email.",
        ["GP_Login_SignIn"] = "Sign In",
        ["GP_Login_SigningIn"] = "Signing in…",
        ["GP_Login_InvalidCredentials"] = "Invalid email or booking reference.",
        ["GP_Login_NetworkError"] = "A network error occurred. Please try again.",
        ["GP_Login_DataProtected"] = "Your data is protected. We never share your information.",
        ["GP_Login_NeedHelp"] = "Need help? Contact our support team",
        ["GP_Login_EmailRequired"] = "Please enter a valid email address.",
        ["GP_Login_RefRequired"] = "Please enter your booking reference.",
        // Guest Portal Dashboard
        ["GP_Dash_Title"] = "My Dashboard",
        ["GP_Dash_WelcomeBack"] = "Welcome back",
        ["GP_Dash_Overview"] = "Here's an overview of your reservations",
        ["GP_Dash_Upcoming"] = "Upcoming",
        ["GP_Dash_ActiveStay"] = "Active Stay",
        ["GP_Dash_PastStays"] = "Past Stays",
        ["GP_Dash_TotalNights"] = "Total Nights",
        ["GP_Dash_UpcomingReservations"] = "Upcoming Reservations",
        ["GP_Dash_NoUpcoming"] = "No upcoming reservations",
        ["GP_Dash_RecentStays"] = "Recent Stays",
        ["GP_Dash_NoPastStays"] = "No past stays yet",
        // Guest Portal Reservations
        ["GP_Res_Title"] = "My Reservations",
        ["GP_Res_Subtitle"] = "Manage all your bookings in one place",
        ["GP_Res_All"] = "All",
        ["GP_Res_Upcoming"] = "Upcoming",
        ["GP_Res_Past"] = "Past",
        ["GP_Res_Empty"] = "No reservations found",
        ["GP_Res_EmptyDesc"] = "Your reservations will appear here once you have bookings.",
        ["GP_Res_CancelTitle"] = "Cancel Reservation",
        ["GP_Res_CancelAbout"] = "You are about to cancel booking",
        ["GP_Res_CancelUndone"] = "This action cannot be undone.",
        ["GP_Res_CancelReason"] = "Reason for cancellation",
        ["GP_Res_CancelReasonPlaceholder"] = "Please tell us why you're cancelling…",
        ["GP_Res_KeepReservation"] = "Keep Reservation",
        ["GP_Res_CancelConfirm"] = "Cancel Reservation",
        ["GP_Res_Cancelling"] = "Cancelling…",
        ["GP_Res_ProvideReason"] = "Please provide a reason.",
        // Guest Portal Profile
        ["GP_Prof_Title"] = "My Profile",
        ["GP_Prof_Subtitle"] = "Manage your contact information and preferences",
        ["GP_Prof_ContactInfo"] = "Contact Information",
        ["GP_Prof_FirstName"] = "First Name",
        ["GP_Prof_LastName"] = "Last Name",
        ["GP_Prof_Email"] = "Email",
        ["GP_Prof_Phone"] = "Phone",
        ["GP_Prof_Address"] = "Address",
        ["GP_Prof_Nationality"] = "Nationality",
        ["GP_Prof_PreferredLanguage"] = "Preferred Language",
        ["GP_Prof_SaveChanges"] = "Save Changes",
        ["GP_Prof_Marketing"] = "Receive promotional offers and news",
        ["GP_Prof_NotifPrefs"] = "Notification Preferences",
        ["GP_Prof_EmailNotif"] = "Email Notifications",
        ["GP_Prof_BookingConf"] = "Booking confirmations",
        ["GP_Prof_CheckInReminder"] = "Check-in reminders (24h before)",
        ["GP_Prof_CheckOutReminder"] = "Check-out reminders",
        ["GP_Prof_ModificationConf"] = "Modification confirmations",
        ["GP_Prof_PromoOffers"] = "Promotional offers (opt-in)",
        ["GP_Prof_Channels"] = "Channels",
        ["GP_Prof_SavePrefs"] = "Save Preferences",
        ["GP_Prof_PrefsSaved"] = "Preferences saved successfully!",
        ["GP_Prof_LoyaltyProgram"] = "Loyalty Program",
        ["GP_Prof_PointsEarned"] = "Points Earned",
        // Guest Portal Reservation Detail
        ["GP_Detail_Title"] = "Reservation Details",
        ["GP_Detail_BackToReservations"] = "Back to Reservations",
        ["GP_Detail_BookingDetails"] = "Booking Details",
        ["GP_Detail_BookingRef"] = "Booking Reference",
        ["GP_Detail_Hotel"] = "Hotel",
        ["GP_Detail_Room"] = "Room",
        ["GP_Detail_CheckIn"] = "Check-In",
        ["GP_Detail_CheckOut"] = "Check-Out",
        ["GP_Detail_Duration"] = "Duration",
        ["GP_Detail_Guests"] = "Guests",
        ["GP_Detail_TotalAmount"] = "Total Amount",
        ["GP_Detail_BookedOn"] = "Booked On",
        ["GP_Detail_SpecialRequests"] = "Special Requests",
        ["GP_Detail_NoSpecialRequests"] = "No special requests on file.",
        ["GP_Detail_EditSpecialReq"] = "Edit Special Requests",
        ["GP_Detail_SaveRequest"] = "Save Request",
        ["GP_Detail_ModifyDates"] = "Modify Dates",
        ["GP_Detail_NewCheckIn"] = "New Check-In",
        ["GP_Detail_NewCheckOut"] = "New Check-Out",
        ["GP_Detail_UpdateDates"] = "Update Dates",
        ["GP_Detail_CancelReservation"] = "Cancel Reservation",
        ["GP_Detail_CancelWarning"] = "Once cancelled, this action cannot be undone.",
        ["GP_Detail_CancelReason"] = "Reason for cancellation…",
        ["GP_Detail_NotFound"] = "Reservation not found",
        ["GP_Detail_ViewAllReservations"] = "View All Reservations",
        // Calendar
        ["Calendar_Title"] = "Reservation Calendar",
        ["Calendar_QuickNav"] = "Quick date navigation",
        ["Calendar_PreviousWeek"] = "Previous week",
        ["Calendar_GoToToday"] = "Go to today (T)",
        ["Calendar_NextWeek"] = "Next week",
        ["Calendar_NextMonth"] = "Next month",
        ["Calendar_NewReservation"] = "New Reservation",
        ["Calendar_Hotel"] = "Hotel",
        ["Calendar_RoomType"] = "Room Type",
        ["Calendar_Status"] = "Status",
        ["Calendar_DateRange"] = "Date Range",
        ["Calendar_Apply"] = "Apply",
        ["Calendar_Clear"] = "Clear",
        ["Calendar_Confirmed"] = "Confirmed",
        ["Calendar_Pending"] = "Pending",
        ["Calendar_CheckedIn"] = "Checked In",
        ["Calendar_CheckedOut"] = "Checked Out",
        ["Calendar_Cancelled"] = "Cancelled",
        ["Calendar_NoShow"] = "No Show",
        ["Calendar_ReservationDetails"] = "Reservation Details",
        ["Calendar_Close"] = "Close",
        ["Calendar_CancelReservation"] = "Cancel Reservation",
        ["Calendar_NewReservationModal"] = "New Reservation",
        ["Calendar_FirstName"] = "First Name",
        ["Calendar_LastName"] = "Last Name",
        ["Calendar_Email"] = "Email",
        ["Calendar_Phone"] = "Phone",
        ["Calendar_Room"] = "Room",
        ["Calendar_CheckIn"] = "Check-in",
        ["Calendar_CheckOut"] = "Check-out",
        ["Calendar_Guests"] = "Guests",
        ["Calendar_TotalAmount"] = "Total Amount",
        ["Calendar_SpecialRequests"] = "Special Requests",
        ["Calendar_InternalNotes"] = "Internal Notes",
        ["Calendar_ConfirmDateChange"] = "Confirm Date Change",
        ["Calendar_ConfirmModify"] = "You are about to modify this reservation. Please review the changes:",
        ["Calendar_Cancel"] = "Cancel",
        ["Calendar_ConfirmChange"] = "Confirm Change",
        ["Calendar_Yesterday"] = "Yesterday",
        ["Calendar_Last7Days"] = "Last 7 Days",
        ["Calendar_Last30Days"] = "Last 30 Days",
        ["Calendar_LastMonth"] = "Last Month",
        // Widget Keys
        ["Widget_OccupancyRate_Title"] = "Occupancy Rate",
        ["Widget_OccupancyRate_Description"] = "Today, week and month occupancy percentages",
        ["Widget_UpcomingCheckIns_Title"] = "Upcoming Check-ins",
        ["Widget_UpcomingCheckIns_Description"] = "Guests checking in today",
        ["Widget_UpcomingCheckOuts_Title"] = "Upcoming Check-outs",
        ["Widget_UpcomingCheckOuts_Description"] = "Guests checking out today",
        ["Widget_RecentReservations_Title"] = "Recent Reservations",
        ["Widget_RecentReservations_Description"] = "Latest reservations across all properties",
        ["Widget_Notifications_Title"] = "Notifications",
        ["Widget_Notifications_Description"] = "Recent system alerts and notifications",
        ["Widget_Revenue_Title"] = "Revenue",
        ["Widget_Revenue_Description"] = "Current revenue and trends",
        ["Widget_RevenueChart_Title"] = "Revenue Chart",
        ["Widget_RevenueChart_Description"] = "Daily revenue trend for the selected period",
        ["Widget_OccupancyBreakdown_Title"] = "Occupancy Breakdown",
        ["Widget_OccupancyBreakdown_Description"] = "Detailed occupancy metrics across time periods",
        ["Widget_QuickStats_Title"] = "Quick Stats",
        ["Widget_QuickStats_Description"] = "Key statistics at a glance",
        ["Widget_BookingSources_Title"] = "Booking Sources",
        ["Widget_BookingSources_Description"] = "Where your reservations come from",
        ["Widget_GuestSatisfaction_Title"] = "Guest Satisfaction",
        ["Widget_GuestSatisfaction_Description"] = "Feedback and satisfaction metrics",
        ["Widget_StaffPerformance_Title"] = "Staff Performance",
        ["Widget_StaffPerformance_Description"] = "Staff productivity and performance",
        ["Widget_HotelUtilization_Title"] = "Hotel Utilization",
        ["Widget_HotelUtilization_Description"] = "Overall hotel occupancy rates",
        ["Widget_RoomRevenue_Title"] = "Room Revenue",
        ["Widget_RoomRevenue_Description"] = "Revenue breakdown by room type",
        ["Widget_Availability_Title"] = "Room Availability",
        ["Widget_Availability_Description"] = "Current room availability status",
        // Toast Messages
        ["Toast_SaveLayout_Success"] = "Dashboard layout saved successfully!",
        ["Toast_SaveLayout_Failure"] = "Failed to save dashboard layout.",
        ["Toast_ResetLayout_Success"] = "Dashboard layout reset successfully.",
        ["Toast_ResetLayout_Failure"] = "Failed to reset dashboard layout.",
        ["Toast_WidgetAdded_Success"] = "Widget added to dashboard!",
        ["Toast_WidgetAdded_Failure"] = "Failed to add widget to dashboard.",
        ["Toast_WidgetRemoved_Success"] = "Widget removed from dashboard.",
        ["Toast_WidgetRemoved_Failure"] = "Failed to remove widget from dashboard.",
        ["Toast_SettingsSaved_Success"] = "Settings saved successfully!",
        ["Toast_SettingsSaved_Failure"] = "Failed to save settings.",
        // Format Strings
        ["Fmt_Currency"] = "{0:C}",
        ["Fmt_Date"] = "{0:MM/dd/yyyy}",
        ["Fmt_DateTime"] = "{0:MM/dd/yyyy HH:mm}",
        ["Fmt_Duration"] = "{0} days",
        ["Fmt_Person"] = "{0} person",
        ["Fmt_People"] = "{0} people",
        ["Fmt_Percent"] = "{0:P}",
        ["Fmt_Weight"] = "{0:N2} kg",
        ["Fmt_Height"] = "{0:N2} m",
        // Calendar Navigation
        ["Calendar_Previous"] = "Previous",
        ["Calendar_Next"] = "Next",
        ["Calendar_Today"] = "Today",
        ["Calendar_ThisWeek"] = "This Week",
        ["Calendar_ThisMonth"] = "This Month",
        ["Calendar_ThisYear"] = "This Year",
        ["Calendar_CustomRange"] = "Custom Range",
        ["Calendar_SelectDateRange"] = "Select Date Range",
        ["Calendar_From"] = "From",
        ["Calendar_To"] = "To"
    };

    private static readonly Dictionary<string, string> _es = new()
    {
        // Navigation
        ["Nav_Dashboard"] = "Panel",
        ["Nav_Calendar"] = "Calendario",
        ["Nav_Properties"] = "Propiedades",
        ["Nav_Reservations"] = "Reservas",
        ["Nav_Reports"] = "Informes",
        ["Nav_SignIn"] = "Iniciar sesión",
        ["Nav_SignOut"] = "Cerrar sesión",
        ["Nav_MyProfile"] = "Mi perfil",
        ["Nav_ChangePassword"] = "Cambiar contraseña",
        ["Nav_UserManagement"] = "Gestión de usuarios",
        ["Nav_Settings"] = "Configuración",
        ["Nav_HelpSupport"] = "Ayuda y soporte",
        ["Nav_Notifications"] = "Notificaciones",
        ["Nav_Home"] = "Inicio",
        ["Nav_Bookings"] = "Reservas",
        ["Nav_Profile"] = "Perfil",
        // Language selector
        ["Lang_SelectLanguage"] = "Idioma",
        ["Lang_English"] = "English",
        ["Lang_Spanish"] = "Español",
        // Common
        ["Common_Loading"] = "Cargando...",
        ["Common_Save"] = "Guardar",
        ["Common_Cancel"] = "Cancelar",
        ["Common_Edit"] = "Editar",
        ["Common_Delete"] = "Eliminar",
        ["Common_Close"] = "Cerrar",
        ["Common_Refresh"] = "Actualizar",
        ["Common_ViewAll"] = "Ver todo",
        ["Common_Details"] = "Detalles",
        ["Common_Back"] = "Volver",
        ["Common_Yes"] = "Sí",
        ["Common_No"] = "No",
        ["Common_All"] = "Todos",
        ["Common_Search"] = "Buscar",
        ["Common_Filter"] = "Filtrar",
        ["Common_Reset"] = "Restablecer",
        ["Common_Error"] = "Ha ocurrido un error. Por favor, inténtalo de nuevo.",
        ["Common_Success"] = "Operación completada correctamente.",
        ["Common_Required"] = "Este campo es obligatorio.",
        ["Common_Saving"] = "Guardando...",
        ["Common_Modify"] = "Modificar",
        ["Common_NoData"] = "No hay datos disponibles",
        // Admin Login
        ["Login_Title"] = "Iniciar sesión",
        ["Login_WelcomeBack"] = "Bienvenido de nuevo",
        ["Login_Subtitle"] = "Por favor, inicia sesión en tu cuenta",
        ["Login_Email"] = "Correo electrónico",
        ["Login_Password"] = "Contraseña",
        ["Login_RememberMe"] = "Recordarme",
        ["Login_ForgotPassword"] = "¿Olvidaste tu contraseña?",
        ["Login_SignIn"] = "Iniciar sesión",
        ["Login_SigningIn"] = "Iniciando sesión...",
        ["Login_NeedHelp"] = "¿Necesitas ayuda?",
        ["Login_ContactAdmin"] = "Contacta con tu administrador del sistema para acceder a tu cuenta",
        ["Login_SmartBooking"] = "Reservas inteligentes",
        ["Login_Analytics"] = "Analíticas",
        ["Login_Secure"] = "Seguro",
        ["Login_SystemTitle"] = "Sistema de Reservas de Hotel",
        ["Login_SystemSubtitle"] = "Gestión centralizada de todas tus reservas de hotel",
        // Dashboard
        ["Dashboard_Title"] = "Panel",
        ["Dashboard_DateRange"] = "Rango de fechas",
        ["Dashboard_AllHotels"] = "Todos los hoteles",
        ["Dashboard_AutoRefresh"] = "Actualización automática",
        ["Dashboard_AddWidget"] = "Añadir widget",
        ["Dashboard_SaveLayout"] = "Guardar diseño",
        ["Dashboard_ResetLayout"] = "Restablecer",
        ["Dashboard_SelectWidget"] = "Selecciona un widget para añadir a tu panel. Los widgets ya visibles aparecen en gris.",
        ["Dashboard_LoadingWidgets"] = "Cargando widgets…",
        // Notifications
        ["Notif_Title"] = "Centro de notificaciones",
        ["Notif_Subtitle"] = "Gestiona y revisa todas tus notificaciones",
        ["Notif_Settings"] = "Configuración",
        ["Notif_MarkAllRead"] = "Marcar todo como leído",
        ["Notif_Total"] = "Total",
        ["Notif_Unread"] = "Sin leer",
        ["Notif_Today"] = "Hoy",
        ["Notif_Read"] = "Leídas",
        ["Notif_All"] = "Todas",
        ["Notif_Reservations"] = "Reservas",
        ["Notif_Alerts"] = "Alertas",
        ["Notif_AllTypes"] = "Todos los tipos",
        ["Notif_Empty"] = "No se encontraron notificaciones",
        ["Notif_LoadingMore"] = "Cargando más…",
        ["Notif_AllLoaded"] = "Todas las notificaciones cargadas",
        ["Notif_MarkRead"] = "Marcar como leída",
        ["Notif_JustNow"] = "Ahora mismo",
        ["Notif_Notifications"] = "Notificaciones",
        ["Notif_MarkAllReadBtn"] = "Marcar todo como leído",
        ["Notif_ViewAll"] = "Ver todas",
        ["Notif_NoNotifications"] = "Sin notificaciones",
        // Notification Settings
        ["NotifSettings_Title"] = "Configuración de notificaciones",
        ["NotifSettings_Subtitle"] = "Configura cómo y cuándo recibes notificaciones",
        ["NotifSettings_Channels"] = "Canales de notificación",
        ["NotifSettings_ChannelsDesc"] = "Elige cómo quieres recibir las notificaciones.",
        ["NotifSettings_Email"] = "Correo electrónico",
        ["NotifSettings_EmailDesc"] = "Recibir notificaciones por correo electrónico",
        ["NotifSettings_Sms"] = "SMS",
        ["NotifSettings_SmsDesc"] = "Recibir notificaciones por mensaje de texto",
        ["NotifSettings_BrowserPush"] = "Notificaciones del navegador",
        ["NotifSettings_BrowserPushDesc"] = "Recibir notificaciones push del navegador",
        ["NotifSettings_Events"] = "Eventos de notificación",
        ["NotifSettings_EventsDesc"] = "Elige qué eventos activan notificaciones.",
        ["NotifSettings_BookingConf"] = "Confirmaciones de reserva",
        ["NotifSettings_BookingConfDesc"] = "Cuando se crea una reserva",
        ["NotifSettings_CheckIn"] = "Recordatorios de entrada",
        ["NotifSettings_CheckInDesc"] = "24 horas antes del check-in",
        ["NotifSettings_CheckOut"] = "Recordatorios de salida",
        ["NotifSettings_CheckOutDesc"] = "El día del check-out",
        ["NotifSettings_Modification"] = "Confirmaciones de modificación",
        ["NotifSettings_ModificationDesc"] = "Cuando se modifica una reserva",
        ["NotifSettings_Promo"] = "Ofertas promocionales",
        ["NotifSettings_PromoDesc"] = "Ofertas especiales y promociones",
        ["NotifSettings_SavePrefs"] = "Guardar preferencias",
        ["NotifSettings_Saving"] = "Guardando…",
        ["NotifSettings_Saved"] = "Preferencias guardadas correctamente",
        ["NotifSettings_SaveFailed"] = "Error al guardar las preferencias",
        // Guest Portal Layout
        ["GP_GuestPortal"] = "Portal de huéspedes",
        ["GP_SignIn"] = "Iniciar sesión",
        ["GP_SignOut"] = "Cerrar sesión",
        ["GP_Dashboard"] = "Panel",
        ["GP_MyReservations"] = "Mis reservas",
        ["GP_MyProfile"] = "Mi perfil",
        ["GP_AuthRequired"] = "Por favor, inicia sesión para acceder a tu portal de huéspedes.",
        ["GP_Home"] = "Inicio",
        ["GP_Bookings"] = "Reservas",
        ["GP_Profile"] = "Perfil",
        // Guest Portal Login
        ["GP_Login_Title"] = "Acceso de huéspedes",
        ["GP_Login_Subtitle"] = "Accede a tus reservas y perfil",
        ["GP_Login_WelcomeBack"] = "Bienvenido de nuevo",
        ["GP_Login_Desc"] = "Inicia sesión con tu correo y referencia de reserva",
        ["GP_Login_Email"] = "Correo electrónico",
        ["GP_Login_BookingRef"] = "Referencia de reserva",
        ["GP_Login_BookingRefHint"] = "La encontrarás en el correo de confirmación de tu reserva.",
        ["GP_Login_SignIn"] = "Iniciar sesión",
        ["GP_Login_SigningIn"] = "Iniciando sesión…",
        ["GP_Login_InvalidCredentials"] = "Correo o referencia de reserva incorrectos.",
        ["GP_Login_NetworkError"] = "Error de red. Por favor, inténtalo de nuevo.",
        ["GP_Login_DataProtected"] = "Tus datos están protegidos. Nunca compartimos tu información.",
        ["GP_Login_NeedHelp"] = "¿Necesitas ayuda? Contacta con nuestro equipo de soporte",
        ["GP_Login_EmailRequired"] = "Por favor, introduce un correo electrónico válido.",
        ["GP_Login_RefRequired"] = "Por favor, introduce tu referencia de reserva.",
        // Guest Portal Dashboard
        ["GP_Dash_Title"] = "Mi panel",
        ["GP_Dash_WelcomeBack"] = "Bienvenido de nuevo",
        ["GP_Dash_Overview"] = "Aquí tienes un resumen de tus reservas",
        ["GP_Dash_Upcoming"] = "Próximas",
        ["GP_Dash_ActiveStay"] = "Estancia activa",
        ["GP_Dash_PastStays"] = "Estancias pasadas",
        ["GP_Dash_TotalNights"] = "Noches totales",
        ["GP_Dash_UpcomingReservations"] = "Próximas reservas",
        ["GP_Dash_NoUpcoming"] = "No hay próximas reservas",
        ["GP_Dash_RecentStays"] = "Estancias recientes",
        ["GP_Dash_NoPastStays"] = "Aún no hay estancias pasadas",
        // Guest Portal Reservations
        ["GP_Res_Title"] = "Mis reservas",
        ["GP_Res_Subtitle"] = "Gestiona todas tus reservas en un solo lugar",
        ["GP_Res_All"] = "Todas",
        ["GP_Res_Upcoming"] = "Próximas",
        ["GP_Res_Past"] = "Pasadas",
        ["GP_Res_Empty"] = "No se encontraron reservas",
        ["GP_Res_EmptyDesc"] = "Tus reservas aparecerán aquí una vez que tengas reservas.",
        ["GP_Res_CancelTitle"] = "Cancelar reserva",
        ["GP_Res_CancelAbout"] = "Estás a punto de cancelar la reserva",
        ["GP_Res_CancelUndone"] = "Esta acción no se puede deshacer.",
        ["GP_Res_CancelReason"] = "Motivo de cancelación",
        ["GP_Res_CancelReasonPlaceholder"] = "Por favor, indícanos por qué cancelas…",
        ["GP_Res_KeepReservation"] = "Mantener reserva",
        ["GP_Res_CancelConfirm"] = "Cancelar reserva",
        ["GP_Res_Cancelling"] = "Cancelando…",
        ["GP_Res_ProvideReason"] = "Por favor, indica un motivo.",
        // Guest Portal Profile
        ["GP_Prof_Title"] = "Mi perfil",
        ["GP_Prof_Subtitle"] = "Gestiona tu información de contacto y preferencias",
        ["GP_Prof_ContactInfo"] = "Información de contacto",
        ["GP_Prof_FirstName"] = "Nombre",
        ["GP_Prof_LastName"] = "Apellidos",
        ["GP_Prof_Email"] = "Correo electrónico",
        ["GP_Prof_Phone"] = "Teléfono",
        ["GP_Prof_Address"] = "Dirección",
        ["GP_Prof_Nationality"] = "Nacionalidad",
        ["GP_Prof_PreferredLanguage"] = "Idioma preferido",
        ["GP_Prof_SaveChanges"] = "Guardar cambios",
        ["GP_Prof_Marketing"] = "Recibir ofertas promocionales y novedades",
        ["GP_Prof_NotifPrefs"] = "Preferencias de notificación",
        ["GP_Prof_EmailNotif"] = "Notificaciones por correo",
        ["GP_Prof_BookingConf"] = "Confirmaciones de reserva",
        ["GP_Prof_CheckInReminder"] = "Recordatorios de entrada (24h antes)",
        ["GP_Prof_CheckOutReminder"] = "Recordatorios de salida",
        ["GP_Prof_ModificationConf"] = "Confirmaciones de modificación",
        ["GP_Prof_PromoOffers"] = "Ofertas promocionales (opt-in)",
        ["GP_Prof_Channels"] = "Canales",
        ["GP_Prof_SavePrefs"] = "Guardar preferencias",
        ["GP_Prof_PrefsSaved"] = "¡Preferencias guardadas correctamente!",
        ["GP_Prof_LoyaltyProgram"] = "Programa de fidelidad",
        ["GP_Prof_PointsEarned"] = "Puntos acumulados",
        // Guest Portal Reservation Detail
        ["GP_Detail_Title"] = "Detalles de la reserva",
        ["GP_Detail_BackToReservations"] = "Volver a reservas",
        ["GP_Detail_BookingDetails"] = "Detalles de la reserva",
        ["GP_Detail_BookingRef"] = "Referencia de reserva",
        ["GP_Detail_Hotel"] = "Hotel",
        ["GP_Detail_Room"] = "Habitación",
        ["GP_Detail_CheckIn"] = "Entrada",
        ["GP_Detail_CheckOut"] = "Salida",
        ["GP_Detail_Duration"] = "Duración",
        ["GP_Detail_Guests"] = "Huéspedes",
        ["GP_Detail_TotalAmount"] = "Importe total",
        ["GP_Detail_BookedOn"] = "Fecha de reserva",
        ["GP_Detail_SpecialRequests"] = "Peticiones especiales",
        ["GP_Detail_NoSpecialRequests"] = "No hay peticiones especiales registradas.",
        ["GP_Detail_EditSpecialReq"] = "Editar peticiones especiales",
        ["GP_Detail_SaveRequest"] = "Guardar petición",
        ["GP_Detail_ModifyDates"] = "Modificar fechas",
        ["GP_Detail_NewCheckIn"] = "Nueva fecha de entrada",
        ["GP_Detail_NewCheckOut"] = "Nueva fecha de salida",
        ["GP_Detail_UpdateDates"] = "Actualizar fechas",
        ["GP_Detail_CancelReservation"] = "Cancelar reserva",
        ["GP_Detail_CancelWarning"] = "Una vez cancelada, esta acción no se puede deshacer.",
        ["GP_Detail_CancelReason"] = "Motivo de cancelación…",
        ["GP_Detail_NotFound"] = "Reserva no encontrada",
        ["GP_Detail_ViewAllReservations"] = "Ver todas las reservas",
        // Calendar
        ["Calendar_Yesterday"] = "Ayer",
        ["Calendar_Last7Days"] = "Últimos 7 días",
        ["Calendar_Last30Days"] = "Últimos 30 días",
        ["Calendar_LastMonth"] = "Mes anterior",
    };

    private readonly Dictionary<string, string> _strings;

    public HardcodedStringLocalizer(string cultureName)
    {
        var isSpanish = cultureName.StartsWith("es", StringComparison.OrdinalIgnoreCase);
        _strings = isSpanish ? _es : _en;
    }

    public LocalizedString this[string name]
    {
        get
        {
            var found = _strings.TryGetValue(name, out var value);
            return new LocalizedString(name, value ?? name, !found);
        }
    }

    public LocalizedString this[string name, params object[] arguments]
    {
        get
        {
            var ls = this[name];
            return new LocalizedString(name, string.Format(ls.Value, arguments), ls.ResourceNotFound);
        }
    }

    public IEnumerable<LocalizedString> GetAllStrings(bool includeParentCultures)
        => _strings.Select(kv => new LocalizedString(kv.Key, kv.Value, false));
}

/// <summary>
/// Factory that creates HardcodedStringLocalizer instances based on current UI culture.
/// Register as: builder.Services.AddSingleton&lt;IStringLocalizerFactory, HardcodedLocalizerFactory&gt;();
/// </summary>
public class HardcodedLocalizerFactory : IStringLocalizerFactory
{
    public IStringLocalizer Create(Type resourceSource)
        => new HardcodedStringLocalizer(CultureInfo.CurrentUICulture.Name);

    public IStringLocalizer Create(string baseName, string location)
        => new HardcodedStringLocalizer(CultureInfo.CurrentUICulture.Name);
}
